ExamTable/Controllers/ExamTimetableController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using ExamTable.Controllers.algorithm;
using System.Web.Mvc;
using ExamTable.Models;
using ExamTable.Controllers.Utils;
using System.Web;

namespace ExamTable.Controllers
{
    public class ExamTimetableController : Controller
    {
        private ExamContext db = new ExamContext();

        // GET: ExamTimetable
        public ActionResult Index()
        {
            int ver = (int)db.exam_timetable.OrderByDescending(e => e.id).First().version_number; // - 7;
            return View(db.exam_timetable.Where(e => e.version_number >= ver)
                    .OrderByDescending(e => e.version_number)
                    .ThenBy(d => d.is_deleted)
                    .ThenBy(c => c.course_hours)
                    .ThenBy(w => w.weekday)
                    .ThenBy(a => a.course_code)
                    .ThenBy(c => c.section_number)
                    .ToList());
        }

        // GET: ExamTimetable/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            exam_timetable exam_timetable = db.exam_timetable.Find(id);
            if (exam_timetable == null)
            {
                return HttpNotFound();
            }
            return View(exam_timetable);
        }

        // GET: ExamTimetable/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ExamTimetable/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,version_number,program_code,program_title,course_code,course_title,course_hours,section_number,have_final_exam,final_exam_note,room_request,exam_length,weekday,time,room,teacher_name,proctor,is_deleted,created_by,created_on,modified_by,modified_on")] exam_timetable exam_timetable)
        {
            if (ModelState.IsValid)
            {
                GreedyAlgo algo = new GreedyAlgo();
                ExamTables table = algo.arrangeExam();
                int? versionNo;
                if (!(db.exam_timetable.Count() > 0))
                {
                    versionNo = 0;
                }
                else
                {
                    versionNo = db.exam_timetable.OrderByDescending(e => e.id).First().version_number;
                    versionNo++;
                }

                foreach (var item in table.solution)
                {
                    foreach (var singleSession in item.sessionIds)
                    {
                        var section = singleSession.sessionId;
                        exam_timetable.version_number = versionNo;
                        exam_timetable.program_code = db.programs.Find(db.sections.Find(section).program_id).program_code;
                        exam_timetable.program_title = db.programs.Find(db.sections.Find(section).program_id).title;
                        exam_timetable.course_code = db.courses.Find(item.courseId).code;
                        exam_timetable.course_title = db.courses.Find(item.courseId).title;
                        exam_timetable.course_hours = db.courses.Find(item.courseId).hours;
                        exam_timetable.section_number = db.sections.Find(section).section_number;
                        exam_timetable.have_final_exam = db.course_exam.Where(ce => ce.course_id == item.courseId).First().have_final_exam;
                        exam_timetable.final_exam_note = db.course_exam.Where(ce => ce.course_id == item.courseId).First().final_exam_note;
                        exam_timetable.room_request = db.room_type.Find(item.roomType).type;
                        var sectionEntity = db.sections.Find(section);
                        if (sectionEntity != null && db.faculties.Find(sectionEntity.faculty_id) != null) // the function to get teacher name is not right here
                        {
                            exam_timetable.teacher_name = db.faculties.Find(sectionEntity.faculty_id).first_name + " " +
                                db.faculties.Find(sectionEntity.faculty_id).last_name;
                        }
                        else
                        {
                            exam_timetable.teacher_name = "";
                        }

                        if (item.protorId > 0)
                        {
                            exam_timetable.exam_length = db.course_exam.Where(ce => ce.course_id == item.courseId).First().exam_length.ToString();
                            exam_timetable.weekday = getWeekday(item.weekDay);
                            exam_timetable.time = getTime(item.startHour, item.endHour, Convert.ToDouble(exam_timetable.exam_length));
                            exam_timetable.room = db.rooms.Find(item.roomId).name;
                            exam_timetable.proctor = db.faculties.Find(item.protorId).first_name + " " +
                                    db.faculties.Find(item.protorId).last_name;
                        }
                        else
                        {
                            exam_timetable.exam_length = "0";
                            exam_timetable.weekday = "N/A";
                            exam_timetable.time = "";
                            exam_timetable.room = "";
                            exam_timetable.proctor = "";
                        }

                        exam_timetable.is_deleted = false;
                        exam_timetable.created_on = DateTime.Now;
                        db.exam_timetable.Add(exam_timetable);
                        db.SaveChanges();
                    }
                }

                return RedirectToAction("Index");
            }

            return View(exam_timetable);
        }

        private string getTime(int start, int end, double length)
        {
            string tempTime = "";
            if (length % 1 != 0)
            {
                tempTime = start.ToString() + ":00 - " + end.ToString() + ":30";
            }
            else
            {
                tempTime = start.ToString() + ":00 - " + end.ToString() + ":00";
            }

            return tempTime;
        }

        private string getWeekday(int weekday)
        {
            string tempDay = "";
            switch (weekday)
            {
                case 0:
                    tempDay = "Monday";
                    break;
                case 1:
                    tempDay = "Tuesday";
                    break;
                case 2:
                    tempDay = "Wednesday";
                    break;
                case 3:
                    tempDay = "Thursday";
                    break;
                case 4:
                    tempDay = "Friday";
                    break;
                default:
                    break;
            }
            return tempDay;
        }

        // GET: ExamTimetable/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            exam_timetable exam_timetable = db.exam_timetable.Find(id);
            if (exam_timetable == null)
            {
                return HttpNotFound();
            }
            return View(exam_timetable);
        }

        // POST: ExamTimetable/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,version_number,program_code,program_title,course_code,course_title,course_hours,section_number,have_final_exam,final_exam_note,room_request,exam_length,weekday,time,room,teacher_name,proctor,is_deleted,created_by,created_on,modified_by,modified_on")] exam_timetable exam_timetable)
        {
            if (ModelState.IsValid)
            {
                db.Entry(exam_timetable).State = EntityState.Modified;
                //if (exam_timetable.is_deleted != false)
                //{
                //    var tempSchedule = db.exam_timetable.Where(e => e.version_number == exam_timetable.version_number);
                //    foreach (var exam in tempSchedule)
                //    {
                //        exam.is_deleted = true;
                //    }
                //}
                exam_timetable.modified_on = DateTime.Now;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(exam_timetable);
        }

        // GET: ExamTimetable/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            exam_timetable exam_timetable = db.exam_timetable.Find(id);
            if (exam_timetable == null)
            {
                return HttpNotFound();
            }
            return View(exam_timetable);
        }

        // POST: ExamTimetable/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            exam_timetable exam_timetable = db.exam_timetable.Find(id);
            //exam_timetable.is_deleted = true;
            //exam_timetable.modified_on = DateTime.Now;
            db.exam_timetable.Remove(exam_timetable);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

ExamTable/Views/ExamTimetable/Create.cshtml
@model ExamTable.Models.exam_timetable

@{
    ViewBag.Title = "Create New Exam Timetable";
}

<h2>Create New Exam Timetable</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ExamTable/Views/ExamTimetable/Delete.cshtml
@model ExamTable.Models.exam_timetable

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Exam Timetable</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.version_number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.version_number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.program_code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.program_code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.program_title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.program_title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.course_code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.course_code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.course_title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.course_title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.course_hours)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.course_hours)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.section_number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.section_number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.have_final_exam)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.have_final_exam)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.final_exam_note)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.final_exam_note)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.room_request)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.room_request)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.exam_length)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.exam_length)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.weekday)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.weekday)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.time)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.time)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.room)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.room)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.teacher_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.teacher_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.proctor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.proctor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.is_deleted)
        </dt>

        <dd>
            @{ string temp = (bool)Model.is_deleted ? "Yes" : "No";}
            @temp
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.created_by)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.created_by)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.created_on)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.created_on)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.modified_by)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.modified_by)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.modified_on)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.modified_on)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ExamTable/Views/ExamTimetable/Details.cshtml
@model ExamTable.Models.exam_timetable

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Exam Timetable</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.version_number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.version_number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.program_code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.program_code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.program_title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.program_title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.course_code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.course_code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.course_title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.course_title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.course_hours)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.course_hours)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.section_number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.section_number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.have_final_exam)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.have_final_exam)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.final_exam_note)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.final_exam_note)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.room_request)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.room_request)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.exam_length)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.exam_length)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.weekday)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.weekday)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.time)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.time)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.room)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.room)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.teacher_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.teacher_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.proctor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.proctor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.is_deleted)
        </dt>

        <dd>
            @{ string temp = (bool)Model.is_deleted ? "Yes" : "No";}
            @temp
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.created_by)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.created_by)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.created_on)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.created_on)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.modified_by)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.modified_by)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.modified_on)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.modified_on)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ExamTable/Views/ExamTimetable/Index.cshtml
@model IEnumerable<ExamTable.Models.exam_timetable>

@{
    ViewBag.Title = "Exam Timetable";
    //string showPath = (string)TempData["showPath"];
    string filepath = (string)TempData["filepath"];

}

<h2>Exam Timetable</h2>

@*<p>
        <div class="row">
            <div class="col-md-6">@Html.ActionLink("Create New", "Create")</div>
            <div class="col-md-6" style="text-align:right;">
                @using (Html.BeginForm("ExportExcel", "ExamTimetable"))
                {
                    <button type="submit" id="exportBtn" data-loading-text="Waiting For Export..." class="btn btn-primary" autocomplete="off">
                        <span class="glyphicon glyphicon-export" aria-hidden="true"></span>
                        Export table to Excel
                    </button>
                }
            </div>
        </div>

        @if (showPath != null)
        {
            <div class="alert alert-info" role="alert" style="position:fixed;bottom:35px;right:60px;">@showPath</div>
        }
    </p>*@

<p>
    <div class="row">
        <div class="col-md-6">@Html.ActionLink("Create New", "Create")</div>
        <div class="col-md-6" style="text-align:right;">
            @using (Html.BeginForm("ExportExcel", "ExamTimetable"))
            {
                <button type="submit" id="exportBtn" data-loading-text="Waiting For Export..." class="btn btn-primary" autocomplete="off">
                    <span class="glyphicon glyphicon-export" aria-hidden="true"></span>
                    Export table to Excel
                </button>
            }
        </div>
    </div>

    <span hidden>
        @if (filepath != null)
        {

            using (Html.BeginForm("DownloadFile", "ExamTimetable"))
            {
                @Html.Hidden("filepath", filepath);
                <button type="submit" id="downloadFile" class="btn btn-primary"></button>
                <script>
                    $(document).ready(function () {
                        $('#downloadFile').trigger("click");
                    });
                </script>
            }
        }

    </span>

</p>
<table class="table">
    <tr>
        <th>
            @*@Html.DisplayNameFor(model => model.version_number)*@
            Version
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.program_code)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.program_title)
            </th>*@
        <th>
            @Html.DisplayNameFor(model => model.id)
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.course_code)*@
            Course <br />
            Code
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.course_title)*@
            Course <br />
            Title
        </th>
        <th>
            @Html.DisplayNameFor(model => model.course_hours)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.section_number)
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.have_final_exam)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.final_exam_note)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.room_request)
            </th>*@
        <th>
            @Html.DisplayNameFor(model => model.exam_length)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.weekday)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.time)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.room)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.teacher_name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.proctor)
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.is_deleted)*@
            Soft <br />
            Deleted?
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.created_by)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.created_on)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.modified_by)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.modified_on)
            </th>*@
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.version_number)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.program_code)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.program_title)
                </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.course_code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.course_title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.course_hours)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.section_number)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.have_final_exam)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.final_exam_note)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.room_request)
                </td>*@
            <td>
                @*@Html.DisplayFor(modelItem => item.exam_length) hours*@
                @{ string temp3 = double.Parse(item.exam_length) > 0 ? item.exam_length + " hours" : "";}
                @temp3
            </td>
            <td>
                @*@Html.DisplayFor(modelItem => item.weekday)*@
                @{ string temp2 = item.weekday == "N/A" ? "NO EXAM" : item.weekday;}
                @temp2
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.time)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.room)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.teacher_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.proctor)
            </td>
            <td>
                @{ string temp = (bool)item.is_deleted ? "Soft Deleted" : "";}
                @temp
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.created_by)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.created_on)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.modified_by)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.modified_on)
                </td>*@
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.id }) | @Html.ActionLink("Details", "Details", new { id = item.id }) | @Html.ActionLink("Delete", "Delete", new { id = item.id })
            </td>
        </tr>
    }

</table>

@section PageScripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $('#exportBtn').on('click', function () {
                var $btn = $(this).button('loading')
                // business logic...
            });
        });
    </script>
}